theme: jekyll-theme-cayman
title: "Monte-Carlo Graph Search: the Value of Merging Similar States"

github:
  repository_url: https://github.com/eleurent/monte-carlo-graph-search


publication:
  name: ACML 2020
  url: http://www.acml-conf.org/2020/

paper_url: http://proceedings.mlr.press/v129/leurent20a.html
slides_url: paper/talk/talk.pdf

authors:
  - name: Edouard Leurent
    url: http://edouardleurent.com
    affiliation: INRIA SEQUEL, Renault
    affiliation_url: https://team.inria.fr/sequel/

  - name: Odalric-Ambrym Maillard
    url: http://odalricambrymmaillard.neowordpress.fr/
    affiliation: INRIA SEQUEL
    affiliation_url: https://team.inria.fr/sequel/
